---
version: 1.4.0
default-factions-plugin: FactionsPro
groups:
  Youtube:
    nametag: '§l§6[§a{fac_name}§6]&b&l✿§e»﹏§cƴᴏᴜ§7ƭᴜɓε§e﹏«§b✿ &6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&b&l✿§e»﹏§cƴᴏᴜ§7ƭᴜɓε§e﹏«§b✿ &6&r{display_name} &b☞ {msg}'
  Owner:
    nametag: '§l§6[§a{fac_name}§6]&d&l♚§3﹏§bƬổɳɠ§6༒§cƬɦốɳɠ§3﹏§d♚&b&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&d&l♚§3﹏§bƬổɳɠ§6༒§cƬɦốɳɠ§3﹏§d♚&b&r{display_name} &b☞ {msg}'
  Guest:
    nametag: '§l§6[§a{fac_name}§6]&b&l❁§a◕§9﹏§eℳεᵯɓεɾ§9﹏§a◕§b❁&f&r {display_name}'
    chat: '§l§6[§a{fac_name}§6]&b&l❁§a◕§9﹏§eℳεᵯɓεɾ§9﹏§a◕§b❁&f&r {display_name} &7☞ {msg}'
  Admin:
    nametag: '§l§6[§a{fac_name}§6]&d&l♚§3﹏§bᎮɧó§6༒§cƬổɳɠ§3﹏§d♚&3&r{display_name}'
    chat: ' §l§6[§a{fac_name}§6]&d&l♚§3﹏§bᎮɧó§6༒§cƬổɳɠ§3﹏§d♚&3&r{display_name} &b☞ {msg}'
  Police:
    nametag: '§l§6[§a{fac_name}§6]&e&l❂§b◬‿§aℭảɳɧ§d༑§aŞáƫ§b‿◬§e❂&f&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&e&l❂§b◬‿§aℭảɳɧ§d༑§aŞáƫ§b‿◬§e❂&f&r{display_name} &b☞ {msg}'
  Helper:
    nametag: '§l§6[§a{fac_name}§6]&6&l♪§d✦﹏§bᎶιúρ§e❦§3Đỡ§d﹏✦§6♫&f&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&6&l♪§d✦﹏§bᎶιúρ§e❦§3Đỡ§d﹏✦§6♫&f&r{display_name} &6☞ {msg}'
  Builder:
    nametag: '§l§6[§a{fac_name}§6]&c&l♥§e༺‿§aƬɧợ§6༉§dメâƴ§e‿༻§c♥&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&c&l♥§e༺‿§aƬɧợ§6༉§dメâƴ§e‿༻§c♥&f&r{display_name} &6☞ {msg}'
  VIP-I:
    nametag: '§l§6[§a{fac_name}§6]&b&l❖§a↫‿§6ϑ¡ρ§9ᴥ§e1§a‿↬§b❖&f&r {display_name}'
    chat: '§l§6[§a{fac_name}§6]&b&l❖§a↫‿§6ϑ¡ρ§9ᴥ§e1§a‿↬§b❖&f&r {display_name} &6☞ {msg}'
  CoOwner:
    nametag: '§l§6[§a{fac_name}§6]&e&lミ★§a⊶§bℭo§d❍ཡɳεɾ§a⊷§e★彡&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&e&lミ★§a⊶§bℭo§d❍ཡɳεɾ§a⊷§e★彡&6&r{display_name} &6☞ {msg}'
  OP:
    nametag: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§b❍§dƤ§6﹏۩§c☠&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§b❍§dƤ§6﹏۩§c☠&6&r{display_name} &6☞ {msg}'
  Coder:
    nametag: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo§dder§6﹏۩§c☠&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo§dder§6﹏۩§c☠&6&r{display_name} &6☞ {msg}'
...
