---
Luật 1 cho member: Không Chửi Thề,Chửi Bậy Trong Khung Chát
Luật 2 cho member: Không Sử Dụng Hack,Toolbox,Bug,Spam...
Luật 3 cho member: Không Quảng Cáo Server Trong Server
Luật 4 cho member: Không Xin Staff Và Rank Trong Server
Luật 5 cho member: Nạp Thẻ Nhiều Thì Chim Mới To
Luật 6 cho staff: Không Gây War Với Các Server Khác
Luật 7 cho staff: Staff Phải Hoạt Động Mỗi Ngày Ít Nhất 2 Tiếng
Luật 8 cho staff: Không Ban,Kick,Mute,Khiêu Khích Mem Bừa Bãi
Luật 9 cho staff: Không Lẩn Tránh Công Việc Được Giao
Luật 10 cho staff: Giới Thiệu Server Cho Bạn Bè Hoặc Cộng Đồng Biết Nhiều Hơn
...