---
#Автор плагина - Лёша Полищук
#Наша группа - vk.com/mcpe14_plugins
#Цена за Fly 
#Việt hóa - remod: by LYT
amount: 10000 
muaxong: §a✔ Đã mua thành công §eFly
muathatbai: §c✖ Đã mua thất bại §eFly
...