---
show-prefix: true
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
hub-message: Welcome to Hub, {PLAYER}
force-spawn: false
enable-spawn-message: true
spawn-message: Teleported To {WORLD} Spawn
enable-aliases: true
hub:
  world: world
  X: -35.663700
  "Y": 64.000000
  Z: 12.306700
  Yaw: 59
  Pitch: 48
...
