#Configuration file for RestartMe v1.2.0
broadcastInterval: 1200
#Sets the interval of the countdown before broadcast, in seconds
broadcastMessage: "§eMáy chủ sẽ khởi động lại trong {RESTART_FORMAT_TIME}."
#Sets the message format, will broadcast at the intervals set in broadcastInterval
countdownMessage: "Khởi động lại máy chủ trong {RESTART_TIME}..."
#Sets the message format, will broadcast during countdown
displayType: chat
#Sets how players get the countdown message, three options: chat, popup, tip
memoryLimit: 1200M
#Sets the max memory that can be allocated before server restarts due to overload
#B = byte; K = kilobyte; M = megabyte; G = gigabyte; T = terabyte
overloadQuitMessage: "§eMáy chủ đã khởi động lại do quá tải."
#Sets the message sent to a player when they are kicked because of a memory overload
quitMessage: "§aKhởi động lại máy chủ."
#Sets the message sent to a player when they are kicked because of a server restart
restartInterval: 300
#Sets the interval of the server restart, in minutes
restartOnOverload: false
#Set to true to allow server restarts when the server's memory is overloaded
startCountdown: 30
#Sets the time when to initiate a countdown, n seconds from restarting