---
admin bun_skyvn phá nhà mem: true
troll mem: true
Jino_VN cúng ZzSkyhealzZ Phá Sever: true
'hacker ': true
tp: true
:): true
hơi lag nha ad khắc phục. tks: true
sv ngu vl: true
lỗi: true
server mấy lúc hơi lag đoa ạ: true
...
