---
#=================================
#{player}- ชื่อในเกม <<<<<<<
#{group} - ยศ <<<<<<<
#{faction} - แคลน <<<<<<<
#{money} - เงิน <<<<<<<
#{gm} - โหมดเกม
#{IP} - ip ของผู้เล่น <<<<<<<
#{onl} - จำนวนที่ออนไลน์ <<<<<<
#{monl} - max ออนไลน์ <<<<<<<
#{hp} - สถานะสุขภาพ <<<<<<<
#{maxhp} - max สุขภาพ<<<<<<<
#{X} {Y} {Z} - พิกัด <<<<<<<
#{level} - ชื่อโลก <<<<<<<
#{time} - เวลา <<<<<<<
#{id}:{ids} - ID item
#{item} - ชื่อ item
#{tps} - TPS เซิร์ฟเวอร์ <<<<<<<
#{usage}- USAGE เซิร์ฟเวอร์ <<<<<<<
#{tag} - บนหัว <<<<<<<

#{kill} - จำนวนฆาตกรรมทั้งหมด <<<<<<<
#{deaths} - ตายรวม <<<<<<<

#{R1} - สุ่มสีข้อความ มี{R1}ถึง{R15} <<<<<<

#{h} - บาร์ทำให้ชิดขวา[ใส่ทุกครั้งที่ใช้ \n ]<<<<<<
#{n} - ยกบาร์ขึ้น <<<<<<
#\n - ขึ้นบรรทัดใหม่

#=================================

CatPlus: "{h}§l§e[-={R3}Royal §4X {R3}Eagle§r=-§8]§r\n{h}§l§a»§eKính chào§b: §c{R4}{player}§r\n{h}§l§a»§eXếp hạng§b: {R3}{group}§r\n{h}§l§a»§eĐang online trên server§b: §a{onl}§8/§c{monl}§r\n{h}§l§a»§eSố tiền§b: §6{money}§r\n{h}§l§a»§eFaction của bạn§b: §f{faction}§r\n{h}§l§a»§eĐồ vật trên tay§b: {R2}{item}§r\n{h}§l§a»§eID§b: {R1}{id}:{ids}§r\n§r{h}§l§a»§eGiết§b: §c{kill}§r\n{h}§l§a»§eChết§b: §c{deaths}{n}"

#=================================
...